# Exported from Render on 2026-09-07T19:49:08Z
version: "1"
projects:
- name: reflex
  environments:
  - name: Production
    services:
    - type: web
      name: reflex-api
      runtime: python
      repo: https://github.com/NdegwaMark/Reflex
      plan: free
      envVars:
      - key: PYTHON_VERSION
        sync: false
      region: oregon
      buildCommand: poetry install
      startCommand: 'gunicorn wsgi : application'
      autoDeployTrigger: commit
